services:
  postgresql:
    image: postgres:17
    ports:
      - '5432'
    environment:
      - POSTGRES_PASSWORD=Sup3rSecr1tPasw8rd
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgresql:/var/lib/postgresql/data

  test:
    build: ./
    volumes:
      - .:/app
    depends_on:
      - postgresql
    command: 'bin/test'
    environment:
      - RAILS_ENV=test
      - DATABASE_URL=postgresql://postgres:Sup3rSecr1tPasw8rd@postgresql:5432/scimitar-test

volumes:
  postgresql:
